name: Deploy Amaranta Gallery

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar Node (para servir si lo necesitas)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Crear env.json
      run: |
        mkdir -p public
        echo "{ \"GOOGLE_SCRIPT_URL\": \"${{ secrets.GOOGLE_SCRIPT_URL }}\" }" > public/env.json

    - name: Subir a GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
