name: Build Amaranta site

on:
  push:
    branches: [ main ]

jobs:
  generate-env:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Crear env.json con secreto
      run: |
        echo "{ \"GOOGLE_SCRIPT_URL\": \"${{ secrets.GOOGLE_SCRIPT_URL }}\" }" > env.json

    - name: Confirmar contenido
      run: |
        ls -la
        cat env.json

    - name: Subir archivo env.json al branch main
      run: |
        git config user.name "amaranta-bot"
        git config user.email "actions@github.com"
        git add env.json
        git commit -m "build: generar env.json dinámicamente" || echo "No hay cambios"
        git push
