name: Deploy Amaranta Gallery

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias para SOPS
      run: sudo apt-get update && sudo apt-get install -y sops jq

    - name: 🔐 Desencriptar y reemplazar la URL en script.js
      run: |
        URL=$(sops -d env.enc.json | jq -r '.GOOGLE_SCRIPT_URL')
        sed -i "s|__INJECT_GOOGLE_SCRIPT_URL__|$URL|" script.js

    - name: Verificar contenido final
      run: grep GOOGLE_SCRIPT_URL script.js