name: Deploy Amaranta Gallery

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Reemplazar la URL directamente con el secreto
      run: |
        sed -i "s|__INJECT_GOOGLE_SCRIPT_URL__|${{ secrets.GOOGLE_SCRIPT_URL }}|" script.js

    - name: Verificar reemplazo
      run: grep "GOOGLE_SCRIPT_URL" script.js

      